server:
  port: 10086
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      # eureka 服务地址，如果是集群的话；需要指定其它集群eureka地址
      defaultZone: http://127.0.0.1:10086/eureka
    # 不注册自己
    register-with-eureka: false
    # 不拉取服务
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: false
  instance:
    ip-address: 127.0.0.1# ip地址
    prefer-ip-address: true # 更倾向于使用ip，而不是host名
